
import java.io.BufferedOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USUARIO
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHechodatos = new javax.swing.JButton();
        spintamano = new javax.swing.JSpinner();
        lbltxtResultado = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Abrir = new javax.swing.JMenuItem();
        guarda = new javax.swing.JMenuItem();
        mnuNuevo = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Programa para la desviación estándar");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Número de datos");

        btnHechodatos.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnHechodatos.setText("Hecho!");
        btnHechodatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHechodatosActionPerformed(evt);
            }
        });

        lbltxtResultado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbltxtResultado.setText("Resultado");

        lblResultado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblResultado.setText("-------");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contabilidad (3).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltxtResultado)
                    .addComponent(btnNuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(spintamano, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHechodatos)
                        .addGap(153, 153, 153))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spintamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHechodatos)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltxtResultado)
                            .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(btnNuevo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        Abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        Abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpeta.png"))); // NOI18N
        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        jMenu1.add(Abrir);

        guarda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        guarda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disquete.png"))); // NOI18N
        guarda.setText("Guardar");
        guarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardaActionPerformed(evt);
            }
        });
        jMenu1.add(guarda);

        mnuNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuevo.png"))); // NOI18N
        mnuNuevo.setText("Nuevo");
        mnuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNuevo);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salida.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        mnu.setText("Acerca de ");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/idea.png"))); // NOI18N
        jMenuItem1.setText("Desarrolladores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnu.add(jMenuItem1);

        jMenuBar1.add(mnu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   int tamanodearreglo,bandera;
   
  
    private void btnHechodatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHechodatosActionPerformed
        // TODO add your handling code here:
       try{
           tamanodearreglo= Integer.parseInt(spintamano.getValue().toString());
           System.out.println("Se puede sacar numero");
       }catch(Exception errorint){
           System.out.println("Sale a negativo listener");
           Negativo();
           
       }
        
        if(tamanodearreglo<=0){
            System.out.println("sale a negativo listener2");
            Negativo();
            
        }
        else{
            System.out.println("sale a proceso 1 el listener");
        Proceso1();    
            
        }
     
    }//GEN-LAST:event_btnHechodatosActionPerformed

    
    int contador=0,contador2;
    double resultado;

    void Negativo(){
        try{
        tamanodearreglo=Integer.parseInt(JOptionPane.showInputDialog(this,"Ingresa el tamaño del arreglo","Ingresar",JOptionPane.INFORMATION_MESSAGE));
            if (tamanodearreglo<=0){
            System.out.println("Se va a negativo 1");
                Negativo2();
                
            }
            else{
            Proceso1();
            }
        }catch(Exception error2){
        System.out.println("Se va a negativo 2");
            Negativo2();    
        
        }
        
    }
    
    
    void Negativo2(){
        try{
        tamanodearreglo=Integer.parseInt(JOptionPane.showInputDialog(this,"Ingresa el tamaño del arreglo","Ingresar",JOptionPane.INFORMATION_MESSAGE));
            if (tamanodearreglo<=0){
                System.out.println("Se va a negativo 3");
            Negativo();
                
            }
            else{
            Proceso1();
            }
        }catch(Exception error2){
            System.out.println("Se va a negativo 4");
        Negativo();    
        
        }
        
    }
 
    
    void Solicitar1(){
        JOptionPane.showMessageDialog(this, "Ingrese un número válido, los datos almacenados serán borrados");
/*        String bandera2;
        bandera=contador;
            bandera2=String.valueOf(bandera);
            contador2=Integer.parseInt(bandera2);
            System.out.println("Valor del contador al ingresar String: "+contador);
        
        INTENTAMOS COLOCAR ESTE CODIGO PARA PODER MANDAR A LLAMAR LA FUNCION PROCESO1 A PARTIR DEL ULTIMO DIGITO EN EL QUE EL USUARIO SE EQUIVOCO
        PERO AL RETORNAR A PROCESO 1, SI MANTENIA EL VALOR DEL CONTADOR COMO ANTES DE SALIR DEL FOR HACIA EL ERROR
        Y PERMITIA DE NUEVO LA INSERCIÓN DEL NÚMERO, PERO DEJABA CON UN VALOR NULL EL VALOR DEL ARRAY, POR LO QUE AL MANDAR A LLAMAR EN EL FOR DE LAS
        OPERACIONES, SALIA EL ERROR NullPointerException, DEBIDO A QUE INTENTABA ESTABLECER EL VALOR DE UNA VARIABLE EL CUAL NO HABÍA SIDO GUARDADO
        
  */    Limpiar();
    }
    
    void Proceso1(){
    Double[] arreglovariables = new Double[tamanodearreglo];
      double semisumatoria,media,sumatoria=0,varianza;   


        for(contador=contador2;contador<tamanodearreglo;contador++){
            
            
            System.out.println("Valor del contador antes del if: "+contador);
            String temporal;
            temporal=(JOptionPane.showInputDialog(this,"Ingresa el numero: "+(contador+1),"Ingresar",JOptionPane.INFORMATION_MESSAGE));      
            if(temporal.matches("-?\\d+(\\d+)?") == true){    
            arreglovariables[contador]= Double.valueOf(temporal);
            
            bandera=contador;
            contador2=bandera;
            System.out.println("El último valor del arreglo es: "+arreglovariables[contador]);
                System.out.println("Valor del contador al ingresar número "+contador);
                
            }
            else{
                System.out.println("Sale hacia el error de string");
            Solicitar1();    
                
            }
        }
        
        System.out.println("PASO DE UNO A OTRO");

         //calculamos la media
         bandera=0;
         semisumatoria=0;
         
     for(bandera=0;bandera<tamanodearreglo;bandera++){
         
           semisumatoria+=arreglovariables[bandera];
           System.out.println("Calculo de la semisumatoria");
        }  
     media=semisumatoria/tamanodearreglo;
     
   //calculamos la sumatoria de la varianza
     for(bandera=0;bandera<tamanodearreglo;bandera++){
           sumatoria+=((arreglovariables[bandera]-media)*(arreglovariables[bandera]-media));
           System.out.println("Calculo de la sumatoria");
        }
       
   //la dividimos y obetenemos la varianza
   varianza=sumatoria/tamanodearreglo;
   //calculamos la desviación estándar
   resultado=Math.sqrt(varianza);
        System.out.println("Paso a mostrar pantalla");
   
   Mostrarenpantalla();
    
        }
 

void Mostrarenpantalla(){
    lblResultado.setText(String.valueOf(resultado));
}
 
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    Limpiar();
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    void Limpiar(){
         spintamano.setValue(0);
       contador2=0;
       contador=0;
       lblResultado.setText("----");
       bandera=0;
       tamanodearreglo=0;
        System.out.println("Se resetea"); 
    }
    
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    new Devs().setVisible(true);    
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
   System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_mnuNuevoActionPerformed

    private void guardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardaActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_guardaActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        // TODO add your handling code here:
        abrir();
    }//GEN-LAST:event_AbrirActionPerformed
void abrir(){
           int contadordeEntrada,extension;
          String Textodesalida="";
    JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto","estadistica");
        file.addChoosableFileFilter(filtro);
        String nombredearchivo = "",Contenido;
        FileInputStream entrada=null;
        
        if(file.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            nombredearchivo=file.getSelectedFile().getAbsolutePath();
            System.out.println("Algo");
            
            try{
            entrada = new FileInputStream(nombredearchivo);
            
            extension=entrada.read();
            while(extension!=-1){
                
                Textodesalida+=(String.valueOf((char)extension));
                    System.out.println((char)extension);
                    extension=entrada.read();
                
                  
            }
            
            
            lblResultado.setText(Textodesalida);
        }catch(Exception error){
            
            System.out.println("Error: "+error.toString());
        }
            try{
                if(entrada !=null)
                entrada.close();
            }catch(Exception e){
                
            }
        }
        else{
            System.out.println("Hubo un error");
            return;
        }
        
   
        
}
    void guardar(){
         String cadenadeSalida;
         int contadordeSalida;
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto","estadistica");
        file.addChoosableFileFilter(filtro);
        String nombredearchivo = "";
        cadenadeSalida=lblResultado.getText();
        System.out.println(lblResultado.getText());
        if(file.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){ 
            nombredearchivo = file.getSelectedFile().getAbsolutePath(); 
            
             BufferedOutputStream salida;
            try{ //Lo que quieres intentar
            salida = new BufferedOutputStream(new FileOutputStream(nombredearchivo+".estadistica"));
            for(contadordeSalida=0;contadordeSalida<cadenadeSalida.length();contadordeSalida++){
            salida.write(cadenadeSalida.charAt(contadordeSalida));
            }
            salida.flush();
            salida.close();
            
            } catch(Exception error){ //lo que vas a realizar al recibir ese error
                System.out.println("Error critico: "+error.toString());
            }
           
           
        }
        else{
            System.out.println("Hubo un error");
            return;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JButton btnHechodatos;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JMenuItem guarda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lbltxtResultado;
    private javax.swing.JMenu mnu;
    private javax.swing.JMenuItem mnuNuevo;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JSpinner spintamano;
    // End of variables declaration//GEN-END:variables
}
